title: Publications & Blog
description: Papers, projects, and posts.

# Optional, safe plugins that GitHub Pages supports
minima:
  skin: auto
show_excerpts: true

# Show these in the top nav
header_pages:
  - index.md
  - publications.md
  - blog/index.md

# Pretty links
permalink: /:categories/:year/:month/:day/:title/

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Optional but helpful plugins (all allowlisted on GitHub Pages)
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Collections
collections:
  docs:
    output: true
    permalink: /docs/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "single"
      toc: true
      toc_sticky: true
      sidebar:
        nav: "docs"

# Include custom pages folder
include:
  - _pages

# Search
search: true

# (Optional) If you have a baseurl (like for project pages), set it here without trailing slash.
# baseurl: ""
# url: ""   # the base hostname & protocol for your site

# (Optional) Repository metadata (used by MM breadcrumbs / edit links)
# repository: "arijitcodespace/arijitcodespace.github.io"
